{% set version = "0.4.0" %}

package:
  name: xarray-simlab
  version: {{ version }}

source:
  fn: xarray-simlab-{{ version }}.tar.gz
  url: https://github.com/benbovy/xarray-simlab/archive/{{ version }}.tar.gz
  sha256: 22f77782161f816057a3deae747ae334b1a6603acf252226a0316dbe4dd51d07

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - attrs >=18.1.0
    - dask
    - python-graphviz
    - numpy
    - tqdm
    - xarray >=0.10.0,<0.14.1
    - zarr

test:
  imports:
    - xsimlab

about:
  home: https://github.com/benbovy/xarray-simlab
  license: BSD-3-Clause
  license_file: LICENSE
  summary: xarray extension for computer model simulations.

extra:
  recipe-maintainers:
    - benbovy
