{% set name = "xarray-simlab" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92de9fbd55e045b0d0eacbc7334a86108ecd5376973b1ed20b600bbc6521c2d6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs >=19.2
    - dask
    - python-graphviz
    - numpy
    - tqdm
    - xarray >=0.10.0
    - zarr >=2.3.0

test:
  imports:
    - xsimlab

about:
  home: https://github.com/benbovy/xarray-simlab
  license: BSD-3-Clause
  license_file: LICENSE
  summary: xarray extension for computer model simulations.

extra:
  recipe-maintainers:
    - benbovy
