{% set version = "0.4.1" %}

package:
  name: xarray-simlab
  version: {{ version }}

source:
  fn: xarray-simlab-{{ version }}.tar.gz
  url: https://github.com/benbovy/xarray-simlab/archive/{{ version }}.tar.gz
  sha256: 890c97062b197ae350d5ea1c59dd142631d8c2e238550909dc91641b314f55e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs >=18.1.0
    - dask
    - python-graphviz
    - numpy
    - tqdm
    - xarray >=0.10.0
    - zarr >=2.3.0

test:
  imports:
    - xsimlab

about:
  home: https://github.com/benbovy/xarray-simlab
  license: BSD-3-Clause
  license_file: LICENSE
  summary: xarray extension for computer model simulations.

extra:
  recipe-maintainers:
    - benbovy
