{% set version = "0.2.0" %}

package:
  name: xarray-simlab
  version: {{ version }}

source:
  fn: xarray-simlab-{{ version }}.tar.gz
  url: https://github.com/benbovy/xarray-simlab/archive/{{ version }}.tar.gz
  sha256: a12d75872033b0f4fecc8ee674546747b2215d2447d74b947f1986a3460554cb

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - attrs >= 18.1.0
    - numpy
    - xarray >=0.10.0

test:
  imports:
    - xsimlab

about:
  home: https://github.com/benbovy/xarray-simlab
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'xarray extension for computer model simulations.'

extra:
  recipe-maintainers:
    - benbovy
